#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
setxkbmap -option "ctrl:nocaps" &

feh --bg-scale ~/Code/sysconf/blackhole.png &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Start the system tray
tray &

# Start two terminals
gnome-terminal &
gnome-terminal &

# Start a browser
google-chrome &

# Start screensaver
gnome-screensaver &

# Start sound server
pulseaudio --start --log-target=syslog &

gnome-session &

## Set up an icon tray
#stalonetray &
#
## Fire up apps
#
#xscreensaver -no-splash &
#
#if [ -x /usr/bin/nm-applet ] ; then
#   nm-applet --sm-disable &
#fi
#
#exec xmonad
