#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Aniket Deshpande <aniketd@keybase>
# http://github.com/aniketd/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &
setxkbmap -option "ctrl:nocaps" &

# Set conditional xrandr output in case of multi-head setup
if [ -n "$(xrandr -q | grep ' connected' | grep '^HDMI-1')" ]
then
    xrandr --output "eDP-1" --auto --output "HDMI-1" --auto --above "eDP-1"
else
    xrandr --output "eDP-1" --auto --output "HDMI-1" --off
fi

# Set the background wallpaper
#feh --bg-fill ~/Code/sysconf/blackhole.png &
redshift &
feh --bg-fill /home/aniketd/Code/sysconf/fsf-wallpaper.jpg &

# Start a window compositor. This ensures Google Chrome paints correctly.
#xcompmgr -n &

# Start the DUNST notification daemon [its awesome!]
#dunst &

# Start the system tray
#tray &
#stalonetray &

# Start sound server
#pulseaudio --start --log-target=syslog &

#exec xmonad-session
