#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources #xrdb -merge ~/.Xresources &
setxkbmap -option "ctrl:nocaps" &

feh --bg-fill ~/Code/sysconf/blackhole.png &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Start the DUNST notification daemon [its awesome!]
dunst &

# Start the system tray
#tray &
#stalonetray &

# Start a terminal
#gnome-terminal & # moved away from gnome

# Start a browser
#google-chrome &
#brave &

# Start screensaver
#gnome-screensaver &
#xscreensaver -no-splash &

# Start sound server
#pulseaudio --start --log-target=syslog &

#gnome-session &
exec xmonad
